### PR TITLE
Humane Society Donates Large Sum to Rust Foundation

### PR DESCRIPTION
**Pull request by jesseleite**

### CODE REVIEW

**Comment by ChristianPavilonis** [comment]
Left placeholder text will not merge.

**Review by IroncladDev — CHANGES_REQUESTED** [review]
Can you add a category, change up the tags, and add some article content?

**Comment by IroncladDev** [comment]
Also, PR is currently a draft

**Comment by jesseleite** [comment]
Didn't add category though, since it sounds like you're removing that in favour of tags.

Also you'll have to set PR draft status, I don't have permissions for that.

**Review by IroncladDev — APPROVED** [review]

**Pull request merged**
